### ISSUE TITLE
Warn log for using ignoreAspectRatio() in phash()

### ISSUE THREAD

**Issue by VySellathurai** [btd/sharp-phash#2]
When using your lib, I get a warning log telling me that using ignoreAspectRatio() is depreciated.

`DeprecationWarning: ignoreAspectRatio() is deprecated, use resize({ fit: "fill" }) instead`

the solution is to implement your phash() like so :  

```
...
sharp(image)
      .greyscale()
      .resize(SAMPLE_SIZE, SAMPLE_SIZE, { fit: "fill" })
.rotate()
...
```

**Comment by btd** [comment]
Thank you. Will take a look

**Comment by btd** [comment]
fixed
